// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taoosbosxdjalsnrwqln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhb29zYm9zeGRqYWxzbnJ3cWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTU5OTAsImV4cCI6MjA2MzYzMTk5MH0.UvsKWOn-9l-MEzCrtTWsHNmBU68_QO3VV4nQQJ6Q1Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);